version: '3.7'

networks:
  host:
    name: "host"
    external: true
  front: {}
  database: {}
  monitoring: {}

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.38.6
    networks: ["host"]
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  node-exporter:
    image: prom/node-exporter:v1.0.1
    networks: ["host"]
    command: >-
      --path.procfs /host/proc
      --path.sysfs /host/proc
      --collector.filesystem.ignored-mount-points
      "^/(sys|proc|dev|host|etc)($$|/)"
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs

  prometheus:
    image: prom/prometheus:v2.23.0
    networks: ["monitoring"]
    command: >-
      --web.enable-lifecycle
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
    ports:
      - 19090:9090
    volumes:
      - ./prometheus/data:/prometheus
      - ./prometheus/config:/etc/prometheus
    extra_hosts:
      - host.docker.internal:host-gateway

  grafana:
    image: grafana/grafana:7.3.6
    networks: ["monitoring"]
    ports:
      - 13000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/config:/etc/grafana/provisioning

  php:
    image: php:8-fpm-alpine
    networks: ["front", "database"]
    depends_on: ["mariadb"]

  mariadb:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=my-not-so-random-password-123
    networks: ["database"]
