global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []

rule_files: []

scrape_configs:

  - job_name: 'docker'
    dockerswarm_sd_configs:
      - &docker-config
        host: unix:///var/run/docker.sock
        role: nodes
        port: 9323
    relabel_configs: &relabel-node
      - action: labelmap
        regex: __meta_dockerswarm_node_(.+)

  - job_name: 'cadvisor'
    dockerswarm_sd_configs:
      - <<: *docker-config
        port: 8080
    relabel_configs: *relabel-node

  - job_name: 'node'
    dockerswarm_sd_configs:
      - <<: *docker-config
        port: 9100
    relabel_configs: *relabel-node

  - job_name: 'containers'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      # Filter containers without this label
      - source_labels:
        - __meta_dockerswarm_service_label_prom_scrape
        regex: "true"
        action: keep
      # Port to use to scrape the container
      - source_labels:
          - __address__
          - __meta_dockerswarm_service_label_prom_port
        action: replace
        target_label: __address__
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
      # Path of the prometheus metrics endpoint
      - source_labels:
          - __meta_dockerswarm_service_label_prom_path
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      # Only keep containers that should be running.
      - source_labels:
          - __meta_dockerswarm_task_desired_state
        regex: running
        action: keep
      # Drop container definition not reachable
      - source_labels: [__meta_dockerswarm_network_name]
        regex: "prom_monitoring"
        action: keep
      # Retrieve labels from service labels and store them
      - action: labelmap
        regex: __meta_dockerswarm_service_label_(.+)
      - action: labelmap
        regex: __meta_dockerswarm_(service_(name|mode))
      # Replace job value
      - source_labels: [__meta_dockerswarm_service_name]
        action: replace
        target_label: job
        regex: prom_(.+)
        replacement: $1
