scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prom_prometheus:9090']
  - job_name: 'grafana'
    static_configs:
    - targets: ['prom_grafana:3000']
  - job_name: 'docker'
    static_configs:
    - targets: ['host.docker.internal:9323']
  # Add this entry to check node exporter
  - job_name: 'node'
    static_configs:
    - targets: ['host.docker.internal:9100']
