server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: systemd-journal
    journal:
      path: /var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: [ '__journal__hostname' ]
        target_label: host
      - source_labels: [ '__journal__systemd_unit' ]
        target_label: systemd_unit
        regex: '(.+)'
      - source_labels: [ '__journal__systemd_user_unit' ]
        target_label: systemd_user_unit
        regex: '(.+)'
      - source_labels: [ '__journal__transport' ]
        target_label: transport
        regex: '(.+)'
      - source_labels: [ '__journal_priority_keyword' ]
        target_label: severity
        regex: '(.+)'
