apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: monitoring-eni
  labels:
    # Don't forget this label
    # If it's not there, the service monitor will be ignored
    # by the default operated Prometheus
    release: prom
spec:
  podMetricsEndpoints:
  - port: http
  selector:
    matchLabels:
      app: my-app 
