route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m
  receiver: "email+slack"
  routes:
  - receiver: "null"
    matchers:
      - alertname = "QuietHours"
  - receiver: "dba-team"
    matchers:
      - service = "postgresql"
receivers:
  - name: "null"
  - name: email+slack
    email_configs:
      - to: 'my-team@eni.fr'
        from: 'a-team@prometheus.fr'
        smarthost: 'localhost:1025'
        require_tls: false
        # auth_username: 'my-user'
        # auth_password: 'my-password'
        # headers:
          # Subject: '{{ template "custom-function" . }}'
    slack_configs:
      - channel: '#prometheus'
        send_resolved: true
        api_url: https://hooks.slack.com/services/XXXX/XXXX/XXXX
