---
services:
  prometheus:
    image: prom/prometheus:v3.2.1
    ports:
      - 19090:9090
    volumes:
      - ./prometheus/data:/prometheus
      - ./prometheus/config:/etc/prometheus
  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - 13000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/config:/etc/grafana/provisioning
